name: Build for pull request

on:
    pull_request:
        branches:
            - '**'

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            DEV_DB_URL: ${{ secrets.DEV_DB_URL }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            DEV_AWS_ACCESS_KEY: ${{ secrets.DEV_AWS_ACCESS_KEY }}
            DEV_AWS_SECRET_KEY: ${{ secrets.DEV_AWS_SECRET_KEY }}
            DEV_AWS_S3_BUCKET_NAME: ${{ secrets.DEV_AWS_S3_BUCKET_NAME }}
            MAIL_HOST: ${{ secrets.MAIL_HOST }}
            MAIL_EMAIL: ${{ secrets.MAIL_EMAIL }}
            MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        steps:
            -   uses: actions/checkout@v3
            -   name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                    java-version: '17'
                    distribution: 'temurin'
            -   name: Build with Gradle
                uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
                with:
                    arguments: build