name: Deploy for push

on:
  push:
    branches:
      - 'temp/**' # currently use oracle server

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      DEV_DB_URL: ${{ secrets.DEV_DB_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DEV_AWS_ACCESS_KEY: ${{ secrets.DEV_AWS_ACCESS_KEY }}
      DEV_AWS_SECRET_KEY: ${{ secrets.DEV_AWS_SECRET_KEY }}
      DEV_AWS_S3_BUCKET_NAME: ${{ secrets.DEV_AWS_S3_BUCKET_NAME }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_EMAIL: ${{ secrets.MAIL_EMAIL }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Test
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: clean test

      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: clean :archive-web:build

      - name: Make Directory
        run: mkdir -p deploy

      - name: Copy Jar
        run: cp ./archive-web/build/libs/*.jar ./deploy

      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

      - name: Copy script
        run: cp ./script/deploy.sh ./deploy

      - name: Make zip file
        run: zip -r ./archive.zip ./deploy

      - name: AWS configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3 upload
        run: aws s3 cp --region ap-northeast-2 --acl private ./archive.zip s3://archive-depromeet/

      - name: CodeDeploy
        run: aws deploy create-deployment --application-name depromeet-deploy --deployment-group-name depromeet-deploy --s3-location bucket=archive-depromeet,key=archive.zip,bundleType=zip
