name: Deploy for push

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      DEV_DB_URL: ${{ secrets.DEV_DB_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DEV_AWS_ACCESS_KEY: ${{ secrets.DEV_AWS_ACCESS_KEY }}
      DEV_AWS_SECRET_KEY: ${{ secrets.DEV_AWS_SECRET_KEY }}
      DEV_AWS_S3_BUCKET_NAME: ${{ secrets.DEV_AWS_S3_BUCKET_NAME }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -P dev

      - name: Make Directory
        run: mkdir -p deploy

      - name: Copy Jar
        run: cp ./target/*.jar ./deploy

      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

      - name: Copy script
        run: cp ./script/deploy.sh ./deploy

      - name: Make zip file
        run: zip -r ./archive.zip ./deploy

      - name: AWS configuration
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3 upload
        run: aws s3 cp --region ap-northeast-2 --acl private ./archive.zip s3://archive-depromeet/

      - name: CodeDeploy
        run: aws deploy create-deployment --application-name depromeet-deploy --deployment-group-name depromeet-deploy --s3-location bucket=archive-depromeet,key=archive.zip,bundleType=zip